### ISSUE TITLE
Different maps to visualize

### ISSUE THREAD

**Issue by MatharuG** [einarf/beatsaber#1]
Not exactly an issue, but is there a way to visualize the Light Show of other maps besides the MEGALOVANIA Remix? Thanks!

**Comment by einarf** [comment]
Can probably just add some command line arguments changing what is loaded:

https://github.com/einarf/beatsaber/blob/ae8aafa70c8d7b06d26e89c25d314e08c63d327f/beatsaber/main.py#L29-L64

**Comment by MatharuG** [comment]
I'm not that skilled with coding, but I did change some paths related to the map (and it's properties, such as BPM) to the song that I wanted to, but it gave me some `IndexError: list index out of range` , or `ValueError: Event type 5 not supported` (the last one I believe it's map incompatibility?)

Anyway, I'm surprised you replied, since it's been 3 years since you last changed something 😅

**Comment by einarf** [comment]
yeah this was just a fun project created in a hurry to be honest, but I'm still very active in other projects.

I'm guessing there are some new event types added that is not supported. Can you share the song/data?

**Comment by MatharuG** [comment]
> yeah this was just a fun project created in a hurry to be honest, but I'm still very active in other projects.

For something ""created in a hurry"", I'm very impressed by how the lighting turned out to be, and it's very interesting to see how they're generated.

> I'm guessing there are some new event types added that is not supported. 

I believe so... I don't own a VR Kit, but I do believe that Beat Saber has advanced quite a lot in 3 years.

> Can you share the song/data?

Of course! Here's the two songs I'm trying to get the lights from. If you're curious, I'm trying to get the lighting of them for Video Backgrounds on Clone Hero, I think it's quite fitting.

Teminite - Raise The Black Flag (This is the one that goes `IndexError: list index out of range`) : [1c806 (Raise The Black Flag - Bytrius & Reddek).zip](https://github.com/einarf/beatsaber/files/10199112/1c806.Raise.The.Black.Flag.-.Bytrius.Reddek.zip)

Geoxor & SVRGE - DEAD (This is the one that goes `ValueError: Event type 5 not supported`) : [22e5e (DEAD - PogU).zip](https://github.com/einarf/beatsaber/files/10199113/22e5e.DEAD.-.PogU.zip)

👋

**Comment by einarf** [comment]
Did a quick repo cleanup. If you clone and install it agan you can
```
cd 22e5e.DEAD.-.PogU
beatsaber --song song.wav --track ExpertPlusStandard.dat --info info.dat
```
assuming you have converted the song to wav file. It might work out of the box if you have ffmpeg installed.

Updated README to reflect the changes.

**Comment by einarf** [comment]
Also documeted how to move the camera around.

**Comment by MatharuG** [comment]
> Did a quick repo cleanup

Nice!

> assuming you have converted the song to wav file

VLC does open .egg files normally, but it doesn't come with a Conversion Profile for WAV. No problem though, since you can create ones, 

Geoxor & SVRGE - DEAD worked flawlessly! But Raise The Black Flag didn't turned out to be what I was expecting. I guess there's only so much you can do with Stock Beat Saber lighting without Chroma/Heck (Beat Saber Plugin, which Raise The Black Flag does take advantage of).

Well, my "issue" has been resolved! So I'll close this one. Thank you so much einarf, for still being active and adding new functionality to a relatively old ""rushed"" project. :D

**Comment by einarf** [comment]
> VLC does open .egg files normally, but it doesn't come with a Conversion Profile for WAV

Select the "Audio - CD" profile for wav 😄

**Comment by einarf** [comment]
And yes.. It's not that exciting depending on the song. Geoxor & SVRGE - DEAD worked pretty well!
